version: "3.9"

networks:
      Docker_network:
              driver: bridge
services:

  wordpress: 
    depends_on:
      - mariadb
    restart: always
    build:  requirements/wordpress/
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - Docker_network

  nginx:
    depends_on:
      - wordpress
    restart: always
    build: requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - Docker_network
    
  mariadb:
      build: requirements/mariadb/
      restart: always
      ports:
        - "3306:3306"
      env_file:
        - .env
      volumes:
        - mariadb:/var/lib/mysql/
      networks:
        - Docker_network

volumes:
 wordpress:
  driver: local
  driver_opts:
   o: bind
   type: ext4
   device: /home/ayajrhou/data/wordpress
 mariadb:
  driver: local
  driver_opts:
    o: bind
    type: ext4
    device: /home/ayajrhou/data/mariadb
