version: "3.9"

services:

  wordpress: 
    build:  requirements/wordpress/
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html

  nginx:
    build: requirements/nginx/
    ports:
      - "443:443"
      - "80:80" #to remove
    
    volumes:
      - wordpress:/var/www/html
    
  mariadb:
      build: requirements/mariadb/
      ports:
        - "3306:3306"
      env_file:
        - .env
      volumes:
        - mariadb:/var/lib/mysql/

volumes:
 wordpress:
  driver: local
  driver_opts:
   o: bind
   type: ext4
   device: /home/ayajrhou/data/wordpress
 mariadb:
  driver: local
  driver_opts:
    o: bind
    type: ext4
    device: /home/ayajrhou/data/mariadb
